config/routes.rb
ViralDispatch::Application.routes.draw do
  resources :comments

  resources :posts
  root :to => "posts#index"

  scope "auth" do
    get "/:login_type/callback", :to => "users#callback", :as => :login
    get "/logout", :to => "users#logout", :as => :logout
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  has_many :comments, :dependent => :destroy
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login_type, :username
  has_many :comments
  has_many :posts

  validates :login_type, :presence => true
  validates :username, :uniqueness => true

  def self.find_by_username_for_twitter(params)
    where(login_type: "twitter", username: params[:info][:name]).first
  end
  
  def self.find_by_username_for_github(params)
    where(login_type: "github", username: params[:info][:nickname]).first
  end

  def create_user_github(params)
    self.login_type = "github"
    self.username = params[:info][:nickname]
  end

  def create_user_twitter(params)
    self.login_type = "twitter"
    self.username = params[:info][:name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    session['user']
  end

  def require_login
    unless current_user
      redirect_to root_url, error: "Please login to perform that action" 
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, only: [:create, :update, :destroy]

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = User.where(login_type: session["user"][:login_type],username: session["user"][:username]).first

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to @comment.post }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, only: [:create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html
      format.json { render json: @post}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = User.where(login_type: session["user"][:login_type],username: session["user"][:username]).first

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.json { head :no_content }
      #from index is only place we need to ajaxy
      if env["HTTP_REFERER"] == root_url
        format.js
      else
        format.js { render :js => "window.location.href = '#{root_url}'"}
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_existing_user, only: :callback

  def callback
    @user = User.new
    @user.send("create_user_#{request.env['omniauth.auth'][:provider]}",request.env["omniauth.auth"])

    respond_to do |format|
      if @user.save
        session["user"] = {username: @user.username, login_type: @user.login_type}
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { redirect_to root_url, error: "There was an error with signing up with that account." }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def logout
    session.clear
    redirect_to root_url, notice: "Successfully logged out"
  end

  private

  def check_existing_user
    user = User.send("find_by_username_for_#{request.env['omniauth.auth'][:provider]}", request.env["omniauth.auth"])
    if user
      session["user"] = {username: user.username, login_type: user.login_type}
      redirect_to root_url
    else
      logger.info request.env['omniauth.auth'][:provider]
      logger.info request.env['omniauth.auth'][:info]
      logger.info "No previous user found."
      session.clear
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= content_tag_for(:div, comment, :class => "pull-left span10 offset1") do %>
  <div class="line"></div>
  <div class="span1">
    <%= link_to raw("<i class='icon-pencil'></i>"), edit_comment_path(comment)%>
  </div>
  <div class="span6 post_body">
    <a href="#comment_<%=comment.id%>"><small><p class="muted">Commented by <%= comment.user.username %> on <%= comment.created_at.strftime("%B, %e %Y @ %I:%M:%S %p") %></p></small></a>
    <%= comment.body %>
  </div>
  <div class="span1 pull-right">
    <%= link_to (raw"<i class='icon-remove'></i>"), comment, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Comment in this Thread</h3>
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :post_id, { :value => @post.id } %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :rows => 8, :class => "span6" %>
  </div>
  <div class="actions pull-right">
    <%= f.submit :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').remove();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= comment.post_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_message.html.erb
<% flash.keys.each do |key| %>
  <% styles = {:notice => :success, :error => :error, :warrning => :block} %>
  <div class="alert alert-<%= styles[key].to_s %>"><%= flash[key] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViralDispatch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if session["user"] %>
      <p class="pull-right">
      Logged in with <%= session["user"][:login_type].titleize%> | <%= link_to "Logout", logout_url %> </p>
    <% else %>
      <p class="pull-right">
        Login with <%= link_to "GitHub", "/auth/github/" %> | 
        <%= link_to "Twitter", "/auth/twitter/" %>
      </p>
    <% end %>
    <h1 class="title_link"><%= link_to "Viral Message Board", root_url %></h1>
    <div class="navbar">
      <div class="rounded navbar-inner dark-grey">
        <%= link_to raw("<i class='icon-edit'></i> Post"), new_post_path, :class => "btn" %>
      </div>
    </div>
    <%= render :partial => "layouts/message" unless flash.keys.empty? %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table">
    <tr>
  <td>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </td>
  <td>
    <%= f.label :message %><br />
    <%= f.text_area :body, :rows => 8, :class => "span6" %>
  </td>
</tr>
</table>
  <div class="actions pull-right">
    <%= f.submit :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="span1">
  <%= link_to raw("<i class='icon-pencil'></i>"), edit_post_path(post)%>
</div>
<div class="span8">
  <%= link_to post.title, post_path(post) %><br />
  <small><p class="muted">Posted by <%= post.user.username %> on <%= post.created_at.strftime("%B, %e %Y @ %I:%M:%S %p") %></p></small>
</div>
<div class="span1 pull-right">
  <%= link_to (raw"<i class='icon-remove'></i>"), post, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
</div>

app/views/posts/_posts.html.erb
<%= content_tag_for(:div, post, :class =>"pull-left span12") do %>
  <%= render :partial => post %>
<% end %>

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post) %>').remove();

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render :partial => "posts", :collection => @posts.reverse, :as => :post%>

app/views/posts/new.html.erb
<h3>Submit a Post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="post_<%=@post.id%>" class="thread span12">
  <%= render :partial => @post %>
  <div class="span10 post_body offset1">
    <p><%= @post.body %></p>
  </div>
  <div class="comments">
    <%= render :partial => @post.comments %>
  </div>
</div>
<div id="comment_form" class="span12">
  <div class="line"></div>
  <%= render 'comments/form' %>
</div>